# Generated by Django 3.2 on 2021-05-20 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
