# Generated by Django 3.2 on 2021-05-22 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todolist_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='entryTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
